name: Build executable with PyInstaller
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build-default:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build the executable
      uses: docker://cdrx/pyinstaller-windows:python3
      with:
        args: -v "$(pwd):/src/" cdrx/pyinstaller-linux
    - name: Upload the executable
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/windows/*
