name: Generate repository stats
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  generate:
    name: repostats-for-nice-project
    runs-on: ubuntu-latest
    steps:
      - name: generate repository stats
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: Luois45/claim-free-steam-packages
          ghtoken: ${{ secrets.ghrs_github_api_token }}
