name: Update the package_list.txt file
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 30
          retry_wait_seconds: 60
          command: python get_package_list.py
      - name: commit files and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch https://github.com/Luois45/claim-free-steam-packages.git HEAD:auto-update
          git commit -m "Updated Steam package list" -a
          git add -A
          git pull --rebase
          git fetch
          git push -f origin HEAD:auto-update
