name: Update the package_list.txt file
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        run: sudo apt-get install -y python3.11
      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 60
          retry_wait_seconds: 300
          command: python get_package_list.py
      - name: commit files and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch https://github.com/Luois45/claim-free-steam-packages.git HEAD:auto-update
          git commit -m "Updated Steam package list" -a
          git add -A
          git pull --rebase
          git fetch
          git push -f origin HEAD:auto-update
      - name: Create Issue on Failed workflow
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
          assignees: Luois45
